button commit
fintegrate-practicom/website pull request #15
Opened 2024-04-01 11:59 UTC by rachelySh

2024-04-04 03:25 UTC, nechamaLearn commented on Buttons.tsx
> +const Buttons = (props: { value: string | number | boolean | React.ReactElement<any, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | React.ReactPortal | null | undefined; })
למה לאפשר כ"כ הרבה דברים כvalue???

2024-04-04 03:25 UTC, nechamaLearn commented on Buttons.tsx
> + import React from 'react';
תייבאי רק את מה שאת צריכה ולא את ריאקט כולה

2024-04-04 03:25 UTC, nechamaLearn commented on Buttons.tsx
> +            backgroundColor: "#F2CB05",
יש צבעים מוגדרים, תשתמשי בהם
מתוך הרשימה של הtheme

2024-04-04 03:27 UTC, nechamaLearn commented on Buttons.tsx
> +            variant="contained" >{props.value}</Button>
תביאי את הvalue כבר כאוביקט בפני עצמו ולא חלק מהprops

2024-04-04 03:27 UTC, nechamaLearn commented on Buttons.tsx
> +// import React from 'react';
תמחקי קוד מיותר

2024-04-04 03:28 UTC, nechamaLearn commented on src/App.d.ts
מתי הקובץ הזה הוסף, ולמה?

2024-04-04 03:28 UTC, nechamaLearn commented on src/App.tsx
למחוק את כל המיותר!!!!!!!!

2024-04-04 03:29 UTC, nechamaLearn commented on src/App.tsx
> +import React, { useState } from 'react';
אין צורך לייבא את react

2024-04-04 03:29 UTC, nechamaLearn commented on src/App.tsx
> +import Buttons from '../Buttons';
עדיף לקרוא לקומפוננטה ללא s את הרי מדברת על כפתור בודד

2024-04-04 03:29 UTC, nechamaLearn commented on src/App.tsx
> +  const [count, setCount] = useState(0);
מיותר

2024-04-04 03:30 UTC, nechamaLearn commented on src/__tests__/Buttons.test.tsx
> +    expect(true).toBeTruthy()
מה הבדיקה מבצעת???
תוסיפי לפחות 3 בדיקות אמיתיות

2024-04-04 03:31 UTC, nechamaLearn commented on Buttons.tsx
> +const Buttons = (props: { value: string | number | boolean | React.ReactElement<any, string | React.JSXElementConstructor<any>> | Iterable<React.ReactNode> | React.ReactPortal | null | undefined; })
מה עם הfunction שתתרחש בonClick?
תקבלי אותה גם כprop

2024-04-10 19:54 UTC, nechamaLearn requested changes

2024-04-10 19:54 UTC, nechamaLearn commented on Button.tsx
> +const Button = (props: any) => {
תהפכי את זה לאוביקט מוגדר וברור, מה בדיוק הprops שצריך לשלוח
(אחרת מה הענין בtsx)

2024-04-10 19:54 UTC, nechamaLearn commented on package.json
> +    "preview": "vite preview"
לא אמור להיות כאן

2024-04-10 19:54 UTC, nechamaLearn commented on src/main.tsx
> +// import React from 'react'
למחוק!!!!

2024-04-10 19:54 UTC, nechamaLearn commented on tsconfig.json
> +  "compilerOptions": {
תביני את ההגדרות ותסנני

2024-04-10 19:54 UTC, nechamaLearn commented on vite.config.js
הקובץ הזה לא אמור להיות תחת nest

2024-05-02 13:23 UTC, rachelySh commented on vite.config.js
תחת nest???
אני בreact
לא הבנתי

2024-05-02 13:26 UTC, rachelySh commented on tsconfig.json
> +  "compilerOptions": {
אני מחקתי את הירוקים 
והשארתי את מה שלא
אבל חשבתי שזה בסדר כי בכל מקרה כשאני "ימרג'ג'" את הפרויקט אני יקבל את הtsconfig של כולם

2024-05-20 08:19 UTC, nechamaLearn commented on vite.config.js
תסתכלי על הנתיב של הקובץ הזה
הוא מחוץ לריאקט

2024-05-20 08:19 UTC, nechamaLearn commented on tsconfig.json
> +  "compilerOptions": {
את תבחרי את של מי לקבל כי יהיה לך קונפליקט

2024-05-20 08:21 UTC, nechamaLearn commented on vite.config.js
צודקת
טעיתי

2024-06-06 12:32 UTC, merged