Adding an .env.example file ( for the website )
fintegrate-practicom/website pull request #17
Opened 2024-04-01 16:26 UTC by tamarfridlis

Adding an .env.example file, as well as adding pages - .env and .env local to the .gitignore page that did not appear there.

2024-04-04 03:39 UTC, nechamaLearn requested changes

2024-04-04 03:39 UTC, nechamaLearn commented on .gitignore
תמנעי את כל הקבצים שמתחילים ב.env

2024-04-04 03:39 UTC, nechamaLearn commented on .env.example
מה המטרה של הקובץ הזה?

2024-04-08 11:10 UTC, tamarfridlis commented on .gitignore
בסדר
אכן מנעתי

2024-04-08 11:10 UTC, tamarfridlis commented on .env.example
בקובץ .env.example יהיו רשומים אילו משתני סביבה כל משתמש יצטרך לשים בפרויקט שלו כשאותם משתנים רגישים עלו לגיט בדף רגיל .env ב.gitignore ומוסתרים למשתמש

2024-04-09 10:03 UTC, nechamaLearn approved these changes

2024-04-09 10:14 UTC, merged