Update_Reducer_To_Web_Site_And_Prettier
fintegrate-practicom/website pull request #25
Opened 2024-04-04 18:37 UTC by eb59162

2024-04-14 09:23 UTC, nechamaLearn requested changes

2024-04-14 09:23 UTC, nechamaLearn commented on .prettierrc
> +  "printWidth": 60,
זה ממש ממש קטן
תעלו ל80

2024-04-14 09:23 UTC, nechamaLearn commented on .prettierrc
> +  "tabWidth": 4,
שילוב של רוחב 60 וטאב של 4
יגרום שמהר מאוד הקוד יכיל המון שורות מיותרות ומעצבנות
תקטינו ל2

2024-04-14 09:23 UTC, nechamaLearn commented on .prettierrc
> +  "jsxSingleQuote": false,
כדאי שזה יהיה אחיד בjs ובjsx (שורות 7-8)

2024-04-14 09:23 UTC, nechamaLearn commented on src/App.jsx
> +
מיותר (תריצי פרטייר)

2024-04-16 12:27 UTC, eb59162 commented on .prettierrc
> +  "printWidth": 60,
תקנתי

2024-04-16 12:28 UTC, eb59162 commented on .prettierrc
> +  "tabWidth": 4,
תקנתי

2024-04-16 12:28 UTC, eb59162 commented on .prettierrc
> +  "jsxSingleQuote": false,
תקנתי

2024-04-16 12:28 UTC, eb59162 commented on .prettierrc
> +  "jsxSingleQuote": false,
תקנתי

2024-04-16 12:29 UTC, eb59162 commented on src/App.jsx
> +
הרצתי

2024-04-16 14:05 UTC, merged