fix the menu
fintegrate-practicom/website pull request #28
Opened 2024-04-14 15:34 UTC by efratCohen-dev

2024-04-15 08:37 UTC, nechamaLearn requested changes

2024-04-15 08:37 UTC, nechamaLearn commented on src/components/menu/SideMenu.tsx
> +const Settings = lazy(() => import('./Try'))
מה המשמעות של היבוא של  try?

2024-04-15 08:37 UTC, nechamaLearn commented on src/components/menu/SideMenu.tsx
> +  const [menuItem, setMenuItem] = useState([
תוציאי את זה לprop חיצוני שמגיע ממנהל הsidemenu

2024-04-15 08:37 UTC, nechamaLearn commented on src/components/menu/SideMenu.tsx
> +        <Route path="/בית" element={<Suspense fallback={<h1>loading..</h1>}><Home /></Suspense>} />
אני מצפה לקבל גם את הelement מהlist וכמובן שגם את path

2024-04-15 08:37 UTC, nechamaLearn commented on src/components/menu/SideMenu.tsx
> +        <Route path="/בית" element={<Suspense fallback={<h1>loading..</h1>}><Home /></Suspense>} />
path חייב להיות באנגלית

2024-04-15 08:47 UTC, efratCohen-dev commented on src/components/menu/SideMenu.tsx
> +const Settings = lazy(() => import('./Try'))
אין משמעות סתם בשביל הבדיקה שלי

2024-04-15 16:04 UTC, nechamaLearn requested changes

2024-04-15 16:04 UTC, nechamaLearn commented on src/components/menu/SideMenu.tsx
> +const ResponsiveDrawer: FC<Props> = ({ items }) => {
הייתי נותנת לזה שם אחר
sideMenu לדוג'

2024-04-15 16:04 UTC, nechamaLearn commented on src/components/menu/SideMenu.tsx
> +              <ListItemButton sx={{ px: 4 }} onClick={listItem.text === 'הגדרות' ? handleDrawerClose : handleDrawerOpen}>
אשמח לדבר איתך על זה, לא ברור לי מה בדיוק המשמעות של הonclick

2024-04-15 16:04 UTC, nechamaLearn commented on src/components/menu/types.tsx
> +     icon:iconsMaterial.SvgIconComponent;
הייתי מוסיפה גם link או path

2024-04-16 06:16 UTC, efratCohen-dev commented on src/components/menu/SideMenu.tsx
> +              <ListItemButton sx={{ px: 4 }} onClick={listItem.text === 'הגדרות' ? handleDrawerClose : handleDrawerOpen}>
המשמעות של הonclick זה שכשילחצו על הגדרות הmenuSide יקטן וישארו רק האיקונים

2024-04-16 12:35 UTC, nechamaLearn commented on src/components/menu/SideMenu.tsx
> +              <ListItemButton sx={{ px: 4 }} onClick={listItem.text === 'הגדרות' ? handleDrawerClose : handleDrawerOpen}>
אבל זה יקרה רק בהגדרות?
אולי תתני הגדרה נוספת שתהיה על כל שורה בנפרד, והיא תחליט אם זה יקטן או לא
או שבכל מקרה זה יקטן
וחוץ מזה, אני מצפה שבonClick זה גם יפתח את העמוד הפנימי
לדעתי תוציאי את זה לפונקציה שתקראי לה, וככה תוכלי לכתוב יותר קוד, וגם יהיה קל יותר לעדכן אותה

2024-05-07 05:45 UTC, nechamaLearn commented on src/components/menu/SideMenu.tsx
> +              <ListItemButton sx={{ px: 4 }} onClick={listItem.text === 'הגדרות' ? handleDrawerClose : handleDrawerOpen}>
מה עם זה?

2024-05-07 07:18 UTC, efratCohen-dev commented on src/components/menu/SideMenu.tsx
> +              <ListItemButton sx={{ px: 4 }} onClick={listItem.text === 'הגדרות' ? handleDrawerClose : handleDrawerOpen}>
אני עכשיו משנה את הonclick על הגדרות

2024-05-07 07:22 UTC, efratCohen-dev commented on src/components/menu/SideMenu.tsx
> +              <ListItemButton sx={{ px: 4 }} onClick={listItem.text === 'הגדרות' ? handleDrawerClose : handleDrawerOpen}>
אבל לא הבנתי מה הכוונה של השורה הזאת :
אני מצפה שבonClick זה גם יפתח את העמוד הפנימי
אמרת להוציא את הrout לדף אחר לא?

2024-05-20 12:12 UTC, nechamaLearn approved these changes

2024-05-20 12:15 UTC, merged