build nest project
fintegrate-practicom/website pull request #34
Opened 2024-05-02 20:15 UTC by efratCohen-dev

2024-05-07 05:53 UTC, nechamaLearn requested changes

2024-05-07 07:24 UTC, efratCohen-dev commented on tsconfig.json
> +    "module": "commonjs",
לא הוספתי כלום בtsconfig.json

2024-05-07 07:26 UTC, efratCohen-dev commented on .prettierrc
אוקי .
מה לגבי הeslint והhusky צריך לעשות גם על הnest ?

2024-05-09 13:49 UTC, nechamaLearn commented on .prettierrc
כן
תתעלמי מזה כרגע כי צריך להתקדם
תיצרי על זה משימה

2024-05-09 13:50 UTC, nechamaLearn requested changes

2024-05-09 13:50 UTC, nechamaLearn commented on .prettierrc
ולא העתקת...

2024-05-09 14:12 UTC, efratCohen-dev commented on .prettierrc
העתקתי אני עכשיו יעלה את הcommit הטוב

2024-05-13 12:19 UTC, nechamaLearn approved these changes

2024-05-13 12:19 UTC, merged