my first header
fintegrate-practicom/website pull request #5
Opened 2024-03-26 14:44 UTC by csy131313

2024-04-04 03:15 UTC, nechamaLearn commented on src/features/Header.tsx
> +import React from 'react';
תייבאי רק את הפונקציות הנדרשות ולא את כל ריאקט

2024-04-04 03:15 UTC, nechamaLearn commented on src/features/Header.tsx
> +  myComponent: string;
הייתי משנה לserviceName

2024-04-04 03:15 UTC, nechamaLearn commented on src/features/Header.tsx
> +          {/* {user && <Avatar alt="User Avatar" src={user.imageUrl} />} */}
למה בהערה?

2024-04-04 08:52 UTC, csy131313 commented
שמתי את השורה בהערה: {/* {user && <Avatar alt="User Avatar"
src={user.imageUrl} />} */}
בגלל שגם השורה של שליפת המשתמש היא בהערה:+// const user =
useSelector((state: RootState) => state.user.currentUser);- בגלל שאיו לי
מושג האם יצרו משתמש נוכחי בסטייט,
ואין לי איך להשתמש בuser במהלך הקומפוננטה.
האם יש אפשרות אחרת לעבוד עד שמתחברים לסטייט??
חוץ מזה אני יושבת כבר כמה ימים על הוספת בדיקות לקומפונננטה,
ישבתי ביחד עם יהודית המנטורית והיא אמרה לי שבגלל שהבנות של חנה בנות את
הפרויקט בjsx ואז הוסיפו על זה קומפונטטות בtsx לחלק מהבנות הפרויקט תקוע
לחלוטין ועושה שגיאות שהיא עדין לא הצליחה לפתור,
גם לי, למרות שניסית כמה פעמים לעבוד לפי מדריכים הגעתי לשגיאות בגלל הבלול
בבניית הפרויקט בין jsx ל-tsx,
אני בגדול כרגע מחכה שהקבוצה של חנה תסדר את הפרויקט יהודית המנטורית אמרה לי
אחרי שעות שניסיתי לסדר את הקונפליקטים שהיא לא ממליצה להמשיך לשבת על זה היות
ובמילא הן צריכות לסדר את הפרויקט.
מה לעשות??

למה בהערה?


‫בתאריך יום ה׳, 4 באפר׳ 2024 ב-6:16 מאת ‪nechamaLearn‬‏ <‪
***@***.***‬‏>:‬

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/features/Header.tsx
> <https://github.com/fintegrate-practicom/website/pull/5#discussion_r1550829926>
> :
>
> > @@ -0,0 +1,53 @@
> +import React from 'react';
>
> תייבאי רק את הפונקציות הנדרשות ולא את כל ריאקט
> ------------------------------
>
> In src/features/Header.tsx
> <https://github.com/fintegrate-practicom/website/pull/5#discussion_r1550830212>
> :
>
> > @@ -0,0 +1,53 @@
> +import React from 'react';
> +import { Link } from 'react-router-dom';
> +import AppBar from ***@***.***/material/AppBar';
> +import Box from ***@***.***/material/Box';
> +import Toolbar from ***@***.***/material/Toolbar';
> +import Typography from ***@***.***/material/Typography';
> +import IconButton from ***@***.***/material/IconButton';
> +import ContactMailIcon from ***@***.***/icons-material/ContactMail';
> +import SettingsIcon from ***@***.***/icons-material/Settings';
> +import Avatar from ***@***.***/material/Avatar';
> +import {  useSelector } from 'react-redux';
> +// import { RootState } from '../types'; // Assuming you have a RootState type defined
> +
> +interface HeaderProps {
> +  myComponent: string;
>
> הייתי משנה לserviceName
> ------------------------------
>
> In src/features/Header.tsx
> <https://github.com/fintegrate-practicom/website/pull/5#discussion_r1550830978>
> :
>
> > +
> +const Header: React.FC<HeaderProps> = ({ myComponent }) => {
> +    //To retrieve a user after creating the state
> +//   const user = useSelector((state: RootState) => state.user.currentUser);
> +
> +  return (
> +    <Box sx={{ flexGrow: 1 }}>
> +      <AppBar position="fixed" sx={{ width: '100%' }}>
> +        <Toolbar>
> +          <img src="/logo.png" style={{ width: "15%" }} />
> +
> +          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
> +            {myComponent || "Send component name in props"}
> +          </Typography>
> +
> +          {/* {user && <Avatar alt="User Avatar" src={user.imageUrl} />} */}
>
> למה בהערה?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fintegrate-practicom/website/pull/5#pullrequestreview-1978591483>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFYDTDD5WEYASN26TC2LZKLY3TAXZAVCNFSM6AAAAABFJCQJB2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNZYGU4TCNBYGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-09 21:38 UTC, nechamaLearn requested changes

2024-04-09 21:38 UTC, nechamaLearn commented on src/componnents/Header/Header.tsx
> +import { FC } from 'react';
תאחדי את שורה 1 ו3

2024-04-09 21:38 UTC, nechamaLearn commented on src/componnents/Header/Header.tsx
> +import { useSelector } from 'react-redux';
אין סיבה לשורות רווח

2024-04-10 07:38 UTC, nechamaLearn approved these changes

2024-05-02 09:56 UTC, closed without merging